// ============================================================
// taskData.js — Centralized mock data & constants for Tasks
// ============================================================

export const TASK_STATUSES = {
  TODO: 'To Do',
  IN_PROGRESS: 'In Progress',
  COMPLETED: 'Completed',
  OVERDUE: 'Overdue',
};

export const STATUS_STYLES = {
  'To Do':      { bg: 'bg-gray-100',   text: 'text-gray-600',   dot: 'bg-gray-400' },
  'In Progress':{ bg: 'bg-blue-100',   text: 'text-blue-700',   dot: 'bg-blue-500' },
  'Completed':  { bg: 'bg-green-100',  text: 'text-green-700',  dot: 'bg-green-500' },
  'Overdue':    { bg: 'bg-red-100',    text: 'text-red-700',    dot: 'bg-red-500' },
};

export const INITIAL_TASKS = [
  {
    id: 1,
    title: 'Submit Q1 Project Report',
    project: 'Annual Planning 2026',
    dateSubmitted: '2026-03-01',
    startDate: '2026-03-01',
    startTime: '09:00',
    endDate: '2026-03-05',
    endTime: '17:00',
    status: 'Overdue',
    dateApproved: null,
    task: '<p>Compile all Q1 deliverables and submit to direct manager for review. Include budget summaries, timeline updates, and team performance metrics.</p>',
    projectLink: 'https://github.com/company/annual-planning',
    assignedBy: 'Maria Santos (HR Manager)',
  },
  {
    id: 2,
    title: 'UI/UX Design Review',
    project: 'HRIS System Revamp',
    dateSubmitted: '2026-03-05',
    startDate: '2026-03-10',
    startTime: '08:00',
    endDate: '2026-03-20',
    endTime: '17:00',
    status: 'In Progress',
    dateApproved: '2026-03-06',
    task: '<p>Review and finalize the UI/UX designs for the HRIS system. Conduct usability testing and document findings.</p><ul><li>Review wireframes</li><li>Conduct user interviews</li><li>Document feedback</li></ul>',
    projectLink: 'https://github.com/company/hris-revamp',
    assignedBy: 'Jose Reyes (CTO)',
  },
  {
    id: 3,
    title: 'Database Optimization',
    project: 'Backend Infrastructure',
    dateSubmitted: '2026-03-08',
    startDate: '2026-03-15',
    startTime: '09:00',
    endDate: '2026-03-25',
    endTime: '18:00',
    status: 'In Progress',
    dateApproved: '2026-03-09',
    task: '<p>Optimize slow database queries and add proper indexing to improve system performance.</p>',
    projectLink: 'https://github.com/company/backend-infra',
    assignedBy: 'Jose Reyes (CTO)',
  },
  {
    id: 4,
    title: 'Review Company Handbook',
    project: 'HR Compliance',
    dateSubmitted: '2026-02-20',
    startDate: '2026-02-20',
    startTime: '10:00',
    endDate: '2026-02-28',
    endTime: '17:00',
    status: 'Completed',
    dateApproved: '2026-03-01',
    task: '<p>Read through the updated company handbook and sign the acknowledgement form.</p>',
    projectLink: '',
    assignedBy: 'Maria Santos (HR Manager)',
  },
  {
    id: 5,
    title: 'Meet with HR Orientation',
    project: 'Onboarding',
    dateSubmitted: '2025-11-01',
    startDate: '2025-11-03',
    startTime: '09:00',
    endDate: '2025-11-05',
    endTime: '12:00',
    status: 'Completed',
    dateApproved: '2025-11-06',
    task: '<p>Attend the HR orientation session and complete all onboarding requirements.</p>',
    projectLink: '',
    assignedBy: 'Maria Santos (HR Manager)',
  },
  {
    id: 6,
    title: 'Sign Employment Contract',
    project: 'Onboarding',
    dateSubmitted: '2025-10-20',
    startDate: '2025-10-24',
    startTime: '09:00',
    endDate: '2025-10-26',
    endTime: '17:00',
    status: 'Completed',
    dateApproved: '2025-10-27',
    task: '<p>Review and sign the employment contract. Ensure all terms are understood.</p>',
    projectLink: '',
    assignedBy: 'Maria Santos (HR Manager)',
  },
  {
    id: 7,
    title: 'Submit 201 File Requirements',
    project: 'Onboarding',
    dateSubmitted: '2025-10-15',
    startDate: '2025-10-18',
    startTime: '09:00',
    endDate: '2025-10-21',
    endTime: '17:00',
    status: 'Completed',
    dateApproved: '2025-10-22',
    task: '<p>Submit all required documents for the 201 file including SSS, PhilHealth, Pag-IBIG, and TIN.</p>',
    projectLink: '',
    assignedBy: 'Maria Santos (HR Manager)',
  },
  {
    id: 8,
    title: 'Prepare Monthly KPI Report',
    project: 'Performance Management',
    dateSubmitted: '2026-03-15',
    startDate: '2026-03-20',
    startTime: '09:00',
    endDate: '2026-04-01',
    endTime: '17:00',
    status: 'To Do',
    dateApproved: null,
    task: '<p>Gather team KPI data and prepare the monthly performance report for management review.</p>',
    projectLink: '',
    assignedBy: 'Maria Santos (HR Manager)',
  },
  {
    id: 9,
    title: 'Conduct Team Stand-up Setup',
    project: 'Team Management',
    dateSubmitted: '2026-03-18',
    startDate: '2026-03-25',
    startTime: '08:30',
    endDate: '2026-04-05',
    endTime: '09:00',
    status: 'To Do',
    dateApproved: null,
    task: '<p>Set up recurring daily stand-up meetings for the team and configure the meeting tools.</p>',
    projectLink: 'https://github.com/company/team-tools',
    assignedBy: 'Jose Reyes (CTO)',
  },
  {
    id: 10,
    title: 'Update Project Documentation',
    project: 'HRIS System Revamp',
    dateSubmitted: '2026-03-20',
    startDate: '2026-03-28',
    startTime: '09:00',
    endDate: '2026-04-10',
    endTime: '18:00',
    status: 'To Do',
    dateApproved: null,
    task: '<p>Update technical documentation and user guides for the HRIS system modules.</p><ul><li>Update API docs</li><li>Revise user manuals</li><li>Add changelog entries</li></ul>',
    projectLink: 'https://github.com/company/hris-revamp/docs',
    assignedBy: 'Jose Reyes (CTO)',
  },
  {
    id: 11,
    title: 'Security Audit Review',
    project: 'IT Security',
    dateSubmitted: '2026-03-22',
    startDate: '2026-04-01',
    startTime: '09:00',
    endDate: '2026-04-15',
    endTime: '18:00',
    status: 'To Do',
    dateApproved: null,
    task: '<p>Participate in the quarterly security audit and provide necessary access credentials and logs.</p>',
    projectLink: '',
    assignedBy: 'Anna Cruz (IT Head)',
  },
  {
    id: 12,
    title: 'Client Presentation Prep',
    project: 'Business Development',
    dateSubmitted: '2026-03-10',
    startDate: '2026-03-12',
    startTime: '09:00',
    endDate: '2026-03-14',
    endTime: '16:00',
    status: 'Completed',
    dateApproved: '2026-03-15',
    task: '<p>Prepare and rehearse the client presentation for the Q2 project pitch.</p>',
    projectLink: '',
    assignedBy: 'Maria Santos (HR Manager)',
  },
];

export const formatDate = (dateStr) => {
  if (!dateStr) return '—';
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
};

export const formatTime = (timeStr) => {
  if (!timeStr) return '—';
  const [h, m] = timeStr.split(':');
  const hour = parseInt(h);
  const ampm = hour >= 12 ? 'PM' : 'AM';
  const h12 = hour % 12 || 12;
  return `${h12}:${m} ${ampm}`;
};
